import * as restate from '@restatedev/restate-sdk'
import { TerminalError, serde } from '@restatedev/restate-sdk'
import { Cron } from 'croner'

let JOB_STATE_NAME = 'principia-job-state'

export const setJobStateName = (jobStateName) => {
	JOB_STATE_NAME = jobStateName
	return JOB_STATE_NAME
}

export const cronJobInitiator = restate.service({
	name: 'CronJobInitiator',
	handlers: {
		create: async (ctx, request) => {
			// Create a new job ID and initiate the cron job object for that ID
			// We can then address this job object by its ID
			const jobId = ctx.rand.uuidv4()
			const job = await ctx.objectClient(cronJob, jobId).initiate(request)
			return `Job created with ID ${jobId} and next execution time ${job.next_execution_time}`
		},
	},
})

export const cronJob = restate.object({
	name: 'CronJob',
	handlers: {
		initiate: async (ctx, request) => {
			if (await ctx.get(JOB_STATE_NAME)) {
				throw new TerminalError('Job already exists for this ID.')
			}

			return await scheduleNextExecution(ctx, request)
		},
		execute: async (ctx) => {
			const jobState = await ctx.get(JOB_STATE_NAME)
			if (!jobState) {
				throw new TerminalError('Job not found.')
			}

			// execute the task
			const { service, method, key, payload } = jobState.request
			if (payload) {
				ctx.genericSend({
					service,
					method,
					parameter: payload,
					key,
					inputSerde: serde.json,
				})
			} else {
				ctx.genericSend({
					service,
					method,
					parameter: undefined,
					key,
					inputSerde: serde.empty,
				})
			}

			await scheduleNextExecution(ctx, jobState.request)
		},
		cancel: async (ctx) => {
			// Cancel the next execution
			const jobState = await ctx.get(JOB_STATE_NAME)
			if (jobState) {
				ctx.cancel(jobState.next_execution_id)
			}

			// Clear the job state
			ctx.clearAll()
		},
		getInfo: restate.handlers.object.shared(async (ctx) => {
			return ctx.get(JOB_STATE_NAME)
		}),
	},
})

const scheduleNextExecution = async (ctx, request) => {
	// Parse cron expression
	// Persist current date in Restate for deterministic replay
	const currentDate = await ctx.date.now()
	let next
	try {
		next = new Cron(request.cronExpression).nextRun(new Date(currentDate))
	} catch (e) {
		throw new TerminalError(`Invalid cron expression: ${e.message}`)
	}
	if (!next) {
		throw new TerminalError(`Cron expression '${request.cronExpression}' has no future run`)
	}

	const delay = next.getTime() - currentDate

	// Schedule next execution for this job
	const thisJobId = ctx.key // This got generated by the CronJobInitiator
	const handle = ctx.objectSendClient(cronJob, thisJobId).execute(restate.rpc.sendOpts({ delay }))

	// Store the job information
	const jobState = {
		request,
		next_execution_time: next.toString(),
		next_execution_id: await handle.invocationId,
	}
	ctx.set(JOB_STATE_NAME, jobState)
	return jobState
}

export { JOB_STATE_NAME }
