import * as restate from '@restatedev/restate-sdk'
import { TerminalError, serde } from '@restatedev/restate-sdk'
import { Cron } from 'croner'
import { sendMessage } from './Admin.js'

let JOB_STATE_NAME = 'empyria-job-state'

export const setJobStateName = (jobStateName) => {
	JOB_STATE_NAME = jobStateName
	return JOB_STATE_NAME
}

/**
 * A retry policy that practically never gives up: it backs off to one attempt a minute and keeps trying. Left to
 * itself Restate stops after 70 attempts (about an hour at this pace) and *pauses* the invocation, and a paused
 * invocation of a virtual object holds the object's lock, so every later call queues behind it for ever. A schedule
 * that was due while the services were down (a restart, a crash, a night off) must simply run when they are back, so
 * jobs use this.
 *
 * The attempt limit is the largest the server accepts. Leaving `maxAttempts` out, or setting it to `Infinity`, does
 * not mean unlimited: the server then applies its own default of 70.
 */
export const RETRY_FOREVER = {
	maxAttempts: 2_147_483_647,
	initialInterval: { seconds: 1 },
	maxInterval: { minutes: 1 },
	exponentiationFactor: 2,
}

export const cronJobInitiator = restate.service({
	name: 'CronJobInitiator',
	handlers: {
		create: async (ctx, request) => {
			// Create a new job ID and initiate the cron job object for that ID
			// We can then address this job object by its ID
			const jobId = ctx.rand.uuidv4()
			const job = await ctx.objectClient(cronJob, jobId).initiate(request)
			return `Job created with ID ${jobId} and next execution time ${job.next_execution_time}`
		},
	},
})

export const cronJob = restate.object({
	name: 'CronJob',
	options: { retryPolicy: RETRY_FOREVER },
	handlers: {
		initiate: async (ctx, request) => {
			if (await ctx.get(JOB_STATE_NAME)) {
				throw new TerminalError('Job already exists for this ID.')
			}

			return await scheduleNextExecution(ctx, request)
		},
		/**
		 * Makes sure this job exists and runs the given request: an idempotent `initiate`, meant for
		 * code that starts with the application and cannot know whether the job was created before.
		 *
		 * - no job yet: schedules it, as `initiate` does;
		 * - the same request already scheduled: changes nothing and returns the current state;
		 * - a different request (another schedule, target or payload): cancels the pending run and
		 *   schedules the new request under the same job ID.
		 */
		ensure: async (ctx, request) => {
			const wanted = normalizeRequest(request)
			const jobState = await ctx.get(JOB_STATE_NAME)

			if (jobState && sameRequest(jobState.request, wanted)) return jobState
			if (jobState) ctx.cancel(jobState.next_execution_id)

			return await scheduleNextExecution(ctx, wanted)
		},
		execute: async (ctx) => {
			const jobState = await ctx.get(JOB_STATE_NAME)
			if (!jobState) {
				throw new TerminalError('Job not found.')
			}

			// execute the task
			const { service, method, key, payload } = jobState.request
			if (payload) {
				ctx.genericSend({
					service,
					method,
					parameter: payload,
					key,
					inputSerde: serde.json,
				})
			} else {
				ctx.genericSend({
					service,
					method,
					parameter: undefined,
					key,
					inputSerde: serde.empty,
				})
			}

			await scheduleNextExecution(ctx, jobState.request)
		},
		cancel: async (ctx) => {
			// Cancel the next execution
			const jobState = await ctx.get(JOB_STATE_NAME)
			if (jobState) {
				ctx.cancel(jobState.next_execution_id)
			}

			// Clear the job state
			ctx.clearAll()
		},
		getInfo: restate.handlers.object.shared(async (ctx) => {
			return ctx.get(JOB_STATE_NAME)
		}),
	},
})

const REQUEST_FIELDS = ['cronExpression', 'service', 'method', 'key', 'payload']

/** Keeps only the fields a job request has, and checks the required ones. */
function normalizeRequest(request) {
	const out = {}
	for (const field of REQUEST_FIELDS)
		if (request?.[field] !== undefined) out[field] = request[field]
	for (const field of ['cronExpression', 'service', 'method']) {
		if (typeof out[field] !== 'string' || out[field].trim() === '') {
			throw new TerminalError(`A cron job needs a non-empty "${field}".`, { errorCode: 400 })
		}
	}
	return out
}

const sameRequest = (a, b) =>
	JSON.stringify(REQUEST_FIELDS.map((f) => a?.[f] ?? null)) ===
	JSON.stringify(REQUEST_FIELDS.map((f) => b?.[f] ?? null))

const scheduleNextExecution = async (ctx, request) => {
	// Parse cron expression
	// Persist current date in Restate for deterministic replay
	const currentDate = await ctx.date.now()
	let next
	try {
		next = new Cron(request.cronExpression).nextRun(new Date(currentDate))
	} catch (e) {
		throw new TerminalError(`Invalid cron expression: ${e.message}`)
	}
	if (!next) {
		throw new TerminalError(`Cron expression '${request.cronExpression}' has no future run`)
	}

	const delay = next.getTime() - currentDate

	// Schedule next execution for this job
	const thisJobId = ctx.key // This got generated by the CronJobInitiator
	const handle = ctx.objectSendClient(cronJob, thisJobId).execute(restate.rpc.sendOpts({ delay }))

	// Store the job information
	const jobState = {
		request,
		next_execution_time: next.toString(),
		next_execution_id: await handle.invocationId,
	}
	ctx.set(JOB_STATE_NAME, jobState)
	return jobState
}

/**
 * Makes sure a recurring job exists, from outside Restate (typically right after the service registered).
 * Safe to call on every start: the job has a stable ID, so a repeat call changes nothing and a changed
 * request replaces the old schedule instead of adding a second job.
 *
 * Needs the `CronJob` object registered on an endpoint.
 * @param {{restateURL: string, id: string, cronExpression: string, service: string, method: string, key?: string, payload?: any}} params
 *   `id` names the job (letters, digits, `.`, `_`, `:`, `-`); `service`/`method`/`key` are the target the
 *   job calls on each run, with `payload` as its input (none when omitted).
 * @returns {Promise<{request: object, next_execution_time: string, next_execution_id: string}>}
 */
export async function ensureCronJob({ restateURL, id, ...request }) {
	if (typeof id !== 'string' || !/^[A-Za-z0-9._:-]+$/.test(id)) {
		throw new TypeError(
			'ensureCronJob needs an id made of letters, digits, ".", "_", ":" and "-"',
		)
	}
	return sendMessage({
		restateURL,
		name: 'CronJob',
		message: 'ensure',
		key: id,
		payload: request,
	})
}

export { JOB_STATE_NAME }
